### PR TITLE
Unicode column names fix

### LINKED ISSUE #280: SparkCompare [PARSE_SYNTAX_ERROR] if column name contains unicode symbols
Script to reproduce:
```
from pyspark.sql import SparkSession
import datacompy

spark = SparkSession.builder.getOrCreate()

df1 = spark.createDataFrame(
    [
        (1, "foo"),
        (2, "bar"),
    ],
    ["id", "例"]
)

df2 = spark.createDataFrame(
    [
        (1, "foo"),
        (2, "baz"),
    ],
    ["id", "例"]
)

comp = datacompy.SparkCompare(spark, df1, df2, join_columns=["例"])
comp.report()
```

It seems that unicode chars are not escaped correctly when building SQL query for compare.

### PR DESCRIPTION
**Pull request by fdosani**
Fixes #280 
@kformanowicz-dotdata would you mind testing this on your end to see if it fixes the program you were having at large?

### CODE REVIEW

**Comment by kformanowicz-dotdata** [comment]
@fdosani Thanks, I confirm it solves the issue I was facing.

**Comment by kformanowicz-dotdata** [comment]
@fdosani When do you plan to release v. 0.11.2 with the fix?

**Comment by fdosani** [comment]
Just need someone to review the PR and I can cut a release asap.

**Review by ak-gupta — APPROVED** [review]

**Comment by fdosani** [comment]
@kformanowicz-dotdata FYI: https://pypi.org/project/datacompy/0.11.2/

**Pull request merged**
