### PR TITLE
Enable Renovate

### PR DESCRIPTION
**Pull request by gliptak**
please configure app/permission to the repo/org at https://github.com/marketplace/renovate

### CODE REVIEW

**Comment by fdosani** [comment]
Not familiar with this app? What is it exactly. Would be helpful to get a sense of the benefit to adding this in.

**Comment by gliptak** [comment]
submit PRs keeping current various dependencies
please see https://github.com/gliptak/hcl2json/pulls?q=is%3Apr+renovate+

**Comment by fdosani** [comment]
> submit PRs keeping current various dependencies
> please see https://github.com/gliptak/hcl2json/pulls?q=is%3Apr+renovate+

We are already using the Edgetest action which does exactly this.

**Comment by gliptak** [comment]
I do see `pytz` somewhat behind at https://github.com/capitalone/datacompy/blob/develop/requirements.txt

https://pypi.org/project/pytz/#history

**Comment by fdosani** [comment]
> I do see `pytz` somewhat behind at https://github.com/capitalone/datacompy/blob/develop/requirements.txt
> 
> https://pypi.org/project/pytz/#history

Not following on your pytz comment?

**Comment by fdosani** [comment]
The Edgetest configuration needs to be updated to push a new requirements.txt which is why you are seeing that with pytz.

**Pull request closed without merging**
