### PR TITLE
Bring Pyspark to 2.4.7 in Travis

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Review by jborchma — APPROVED** [review]
I'm fine with this. This would effectively changing our testing to 2.4.7, which I think is appropriate. What do you think, Faisal?

**Comment by fdosani** [comment]
I think ideally we should move to testing out 2.4.3 -> 3.x if possible. There are several versions now and it would make sense to test out a bunch if possible in Travis.

**Comment by gliptak** [comment]
@fdosani i can submit a follow-up PR with a build matrix

https://github.com/capitalone/datacompy/pull/88

**Comment by fdosani** [comment]
> @fdosani i can submit a follow-up PR with a build matrix
> 
> #88

Awesome thanks, appreciate it. I think something from 2.4.4 -> 3.0.1 / Python 3.6 -> 3.8?

**Review by fdosani — APPROVED** [review]
LGTM

**Pull request merged**
