### PR TITLE
adding Polars v1 tweaks for testing

### LINKED ISSUE #324: Polars v1 support
There are some breaking changes in Polars v1. Need to tweak the tests and some deprecations.

### PR DESCRIPTION
**Pull request by fdosani**
Fixes #324

### CODE REVIEW

**Comment by fdosani** [comment]
ping @ak-gupta @jdawang @gladysteh99 if you have some time this week. No rush.

**Review by jdawang — APPROVED** [review]

**Comment by mark-thm** [comment]
@fdosani possible you can cut a release that includes this change? we'd love to take a polars upgrade but are blocked on datacompy's tight pin for polars, and the 1.1.0 upper bound is still unreleased.

**Comment by fdosani** [comment]
> @fdosani possible you can cut a release that includes this change? we'd love to take a polars upgrade but are blocked on datacompy's tight pin for polars, and the 1.1.0 upper bound is still unreleased.

On it.

**Comment by fdosani** [comment]
@mark-thm https://pypi.org/project/datacompy/0.13.3/

**Comment by mark-thm** [comment]
Thanks!

**Pull request merged**
