### PR TITLE
adding all_rows_overlap to fugue

### PR DESCRIPTION
**Pull request by fdosani**
Ref: https://github.com/capitalone/datacompy/issues/214
Support for all_rows_overlap with Fugue

### CODE REVIEW

**Comment by fdosani** [comment]
@goodwanghan FYI. Had some time, so adding in some more functionality to the Fugue side.

**Comment by goodwanghan** [comment]
Wow nice

**Comment by fdosani** [comment]
> Wow nice

Well this sucks. Seems like the last release of fugue is breaking some of the tests :(

**Comment by goodwanghan** [comment]
Oh what? I will take a look

**Comment by goodwanghan** [comment]
I can reproduce this issue, will take a look today

**Comment by goodwanghan** [comment]
So after some initial investigation, it is related with pandas. Fugue 0.8.7 has a big update that is it relies more on pandas extension d types. It is an interesting case why the current datacompy logic breaks with this change. I will investigate more.

**Comment by fdosani** [comment]
> So after some initial investigation, it is related with pandas. Fugue 0.8.7 has a big update that is it relies more on pandas extension d types. It is an interesting case why the current datacompy logic breaks with this change. I will investigate more.

Ahh interesting. Thanks for helping out here and taking a peek, really appreciate it.

**Comment by goodwanghan** [comment]
no problem, actually think this is a very good case, i have found an example
You know pandas will use object type for string columns, but in new pandas, it can be StringDType, and it can be an arrow type (it is a mess I know). So in this case we want to treat them as the same type? In the current logic, we think they are different. That is why we saw those failed tests.

**Comment by fdosani** [comment]
Gotcha that makes sense. Yeah strings should in theory be the same in that example.   On Fri, Nov 10, 2023 at 1:34 PM, Han Wang ***@***.***> wrote:  
no problem, actually think this is a very good case, i have found an example
You know pandas will use object type for string columns, but in new pandas, it can be StringDType, and it can be an arrow type (it is a mess I know). So in this case we want to treat them as the same type? In the current logic, we think they are different. That is why we saw those failed tests.

**Comment by fdosani** [comment]
> no problem, actually think this is a very good case, i have found an example
> 
> You know pandas will use object type for string columns, but in new pandas, it can be StringDType, and it can be an arrow type (it is a mess I know). So in this case we want to treat them as the same type? In the current logic, we think they are different. That is why we saw those failed tests.
> 
> 
> 
> To generalize, datacompy needs to consider the comparison between original type and extension dtypes, do we think they are the same?
> 
> 
> 
> Examples are:
> 
> 
> 
> object vs StringDType
> 
> int vs Int
> 
> bool vs Bool
> 
> 
> 
> 
> 
> 

Yup those should be considered the same type IMHO.

**Comment by jdawang** [comment]
We should probably list the added functionality for fugue in the docs. Right now only `is_match` and `report` are mentioned.

**Comment by fdosani** [comment]
> We should probably list the added functionality for fugue in the docs. Right now only `is_match` and `report` are mentioned.

Good call! Will add this in a bit.

**Comment by fdosani** [comment]
@jdawang updated now

**Review by jdawang — APPROVED** [review]

**Pull request merged**
