### PR TITLE
Update core.py

### PR DESCRIPTION
**Pull request by pronoym99**
Convert ```format``` strings to python3.6+ compliant ```f-strings``` wherever possible.

### CODE REVIEW

**Comment by pronoym99** [comment]
Please add the hacktoberfest label to this PR.

**Comment by fdosani** [comment]
@pronoym99 I'm happy to accept this PR but if you could do so on the entire code base not just one file that would be helpful.

**Comment by pronoym99** [comment]
Ok..No problem. Shall do the same as soon as possible.

**Comment by fdosani** [comment]
There hasn't been any activity on this PR for a while now. Closing it for now. Feel free to reopen if you have other changes as suggested

**Pull request closed without merging**
